[options]
wait_second = 180
protocol = "someip"


[fields]
service_id = 0x8D03
method_id = 0x0001
protocol_version = 0x01
interface_version = 0x01
message_type = 0x01
return_code = 0x01
payload = [0x00, 0x00, 0x00, 0x01]
