__all__ = ["EntryType"]


from enum import IntEnum


class EntryType(IntEnum):
    FIND_SERVICE = 0x00
    OFFER_SERVICE = 0x01
    STOP_OFFER_SERVICE = 0x01
    SUBSCRIBE_EVENTGROUP = 0x06
    STOP_SUBSCRIBE_EVENTGROUP = 0x06
    SUBSCRIBE_EVENTGROUP_ACK = 0x07
    SUBSCRIBE_EVENTGROUP_NACK = 0x07
